/*
 * File:           C:\Users\marce\OneDrive\Desktop\GitHub Repos\AudioDSP-v2.0\AudioDSP-v2.0\DOC\software\DSP-Loudness\DSP2\IC 2_DSP2\DSP2_IC_2_PARAM.h
 *
 * Created:        Thursday, August 24, 2023 7:17:20 PM
 * Description:    DSP2:IC 2 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2023 Analog Devices, Inc. All rights reserved.
 */
#ifndef __DSP2_IC_2_PARAM_H__
#define __DSP2_IC_2_PARAM_H__


/* Module DC-LED2 - DC Input Entry*/
#define MOD_DC_LED2_COUNT                              1
#define MOD_DC_LED2_DEVICE                             "IC2"
#define MOD_DC_LED2_DCINPALG3_ADDR                     0
#define MOD_DC_LED2_DCINPALG3_FIXPT                    0x00800000
#define MOD_DC_LED2_DCINPALG3_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_DC_LED2_DCINPALG3_TYPE                     SIGMASTUDIOTYPE_FIXPOINT

/* Module VolDC - DC Input Entry*/
#define MOD_VOLDC_COUNT                                1
#define MOD_VOLDC_DEVICE                               "IC2"
#define MOD_VOLDC_DCINPALG1_ADDR                       1
#define MOD_VOLDC_DCINPALG1_FIXPT                      0x00800000
#define MOD_VOLDC_DCINPALG1_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_VOLDC_DCINPALG1_TYPE                       SIGMASTUDIOTYPE_FIXPOINT

/* Module Loudness - Loudness (Low & Hi) External Ctrl*/
#define MOD_LOUDNESS_COUNT                             12
#define MOD_LOUDNESS_DEVICE                            "IC2"
#define MOD_LOUDNESS_ALG0_LEVEL0_ADDR                  2
#define MOD_LOUDNESS_ALG0_LEVEL0_FIXPT                 0x00400000
#define MOD_LOUDNESS_ALG0_LEVEL0_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_LOUDNESS_ALG0_LEVEL0_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_LEVEL1_ADDR                  3
#define MOD_LOUDNESS_ALG0_LEVEL1_FIXPT                 0x00400000
#define MOD_LOUDNESS_ALG0_LEVEL1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_LOUDNESS_ALG0_LEVEL1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_COEFFICIENTS0_ADDR           4
#define MOD_LOUDNESS_ALG0_COEFFICIENTS0_FIXPT          0x00333932
#define MOD_LOUDNESS_ALG0_COEFFICIENTS0_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.400183005102475)
#define MOD_LOUDNESS_ALG0_COEFFICIENTS0_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_COEFFICIENTS1_ADDR           5
#define MOD_LOUDNESS_ALG0_COEFFICIENTS1_FIXPT          0xFFCCC6CE
#define MOD_LOUDNESS_ALG0_COEFFICIENTS1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.400183005102475)
#define MOD_LOUDNESS_ALG0_COEFFICIENTS1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_COEFFICIENTS2_ADDR           6
#define MOD_LOUDNESS_ALG0_COEFFICIENTS2_FIXPT          0x00333932
#define MOD_LOUDNESS_ALG0_COEFFICIENTS2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.400183005102475)
#define MOD_LOUDNESS_ALG0_COEFFICIENTS2_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_COEFFICIENTS3_ADDR           7
#define MOD_LOUDNESS_ALG0_COEFFICIENTS3_FIXPT          0x00010038
#define MOD_LOUDNESS_ALG0_COEFFICIENTS3_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00781926913325381)
#define MOD_LOUDNESS_ALG0_COEFFICIENTS3_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_COEFFICIENTS4_ADDR           8
#define MOD_LOUDNESS_ALG0_COEFFICIENTS4_FIXPT          0x007EFFC7
#define MOD_LOUDNESS_ALG0_COEFFICIENTS4_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.992180730866746)
#define MOD_LOUDNESS_ALG0_COEFFICIENTS4_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_ADDR   9
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_FIXPT  0x00000002
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.38418579101563E-07)
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_ADDR   9
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_FIXPT  0x00000002
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.38418579101563E-07)
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_ADDR   9
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_FIXPT  0x00000002
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.38418579101563E-07)
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_ADDR   9
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_FIXPT  0x00000002
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.38418579101563E-07)
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_ADDR   9
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_FIXPT  0x00000002
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.38418579101563E-07)
#define MOD_LOUDNESS_ALG0_LOUDNESSLHEXTALG1STEP_TYPE   SIGMASTUDIOTYPE_FIXPOINT

#endif
